import type { DriverSettlement, SummaryStats } from './types';

export function calculateSummaryStats(settlements: DriverSettlement[]): SummaryStats {
  let totalPayable = 0;
  let totalRecoverable = 0;
  let pendingApprovals = 0;

  for (const s of settlements) {
    if (s.settlement_type === 'Payable') {
      totalPayable += Math.abs(s.difference_amount);
    } else if (s.settlement_type === 'Recoverable') {
      totalRecoverable += Math.abs(s.difference_amount);
    }
    if (s.status === 'Pending') pendingApprovals++;
  }

  return {
    totalSettlements: settlements.length,
    totalPayable,
    totalRecoverable,
    pendingApprovals,
  };
}

export function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    minimumFractionDigits: 2,
  }).format(amount);
}

export function formatDate(dateStr: string): string {
  if (!dateStr) return '—';
  const d = new Date(dateStr);
  return d.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}

export function exportToCsv(settlements: DriverSettlement[]): void {
  const headers = [
    'Trip ID',
    'Trip Date',
    'Driver Name',
    'Driver ID',
    'Vehicle Number',
    'Route',
    'Advance (INR)',
    'Trip Expenses (INR)',
    'Difference (INR)',
    'Settlement Type',
    'Status',
    'Payment Reference',
    'Payment Date',
    'Notes',
    'Generated By',
    'Generated At',
    'Approved By',
    'Approved At',
  ];

  const rows = settlements.map((s) => [
    s.trip_id,
    s.trip_date,
    s.driver_name,
    s.driver_id,
    s.vehicle_number ?? '',
    s.route ?? '',
    s.advance_amount,
    s.trip_expenses_total,
    s.difference_amount,
    s.settlement_type,
    s.status,
    s.payment_reference ?? '',
    s.payment_date ?? '',
    s.notes ?? '',
    s.generated_by ?? '',
    s.generated_at ? new Date(s.generated_at).toLocaleString('en-IN') : '',
    s.approved_by ?? '',
    s.approved_at ? new Date(s.approved_at).toLocaleString('en-IN') : '',
  ]);

  const csvContent = [headers, ...rows]
    .map((row) => row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(','))
    .join('\n');

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  const today = new Date().toISOString().split('T')[0];
  link.href = url;
  link.download = `driver-settlements-${today}.csv`;
  link.click();
  URL.revokeObjectURL(url);
}
